steps:
  - name: gcr.io/kaniko-project/executor:v1.6.0
    args:
      - --destination=gcr.io/low-traffic/rembg
      - --cache=true
      - --cache-ttl=12h
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'rembg',
        '--image',
        'gcr.io/low-traffic/rembg',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--quiet',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'services',
        'update-traffic',
        'rembg',
        '--to-latest',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--quiet',
      ]
timeout: 1200s
